ROSTemplateFormatVersion: "2015-09-01"
Description: "OpenShift on AliBaba Cloud Developer Preview"
Parameters:
  # General
  RegionId:
    Type: String
    Default: eu-central-1
  EnvId:
    Type: String
    Default: lab-ay1
  CreateSnoCluster:
    Description: "Whether a Single-Node cluster"
    Type: Boolean
    Default: false
  CreateCompactCluster:
    Description: "Whether a 3-Node compact cluster"
    Type: Boolean
    Default: false
  # Networking
  VpcCidrBlock:
    Type: String
    Default: "192.168.0.0/16"
  VpcName:
    Type: String
    Default: ay-cluster-vpc
  VSwitchCidrBlockA:
    Type: String
    Default: "192.168.1.0/24"
  VSwitchCidrBlockB:
    Type: String
    Default: "192.168.2.0/24"
  VSwitchAName:
    Type: String
    Default: ay-vswitch-a
  VSwitchBName:
    Type: String
    Default: ay-vswitch-b
  SecurityGroupName:
    Type: String
    Default: ay-cluster-sg
  # Security
  SSHPublicKeyBody:
    Description: "The file content of the SSH public key file"
    Type: String
  # ECS
  MasterInstanceType:
    Type: String
    Default: ecs.g6.xlarge
  WorkerInstanceType:
    Type: String
    Default: ecs.g6.large
  InternetMaxBandwidthOut:
    Type: Number
    Default: 100
  AIImageId:
    Type: String
  InstanceSystemSize:
    Type: Number
    Default: 100
  InstanceDataSize:
    Type: Number
    Default: 100
  DomainName:
    Type: String
    Default: "alicloud-dev.devcluster.openshift.com"
  ClusterName:
    Type: String
    Default: "lab-aliyun-cluster"
  BationHostFlag:
    Description: "Whether to create a bastion host"
    Type: Boolean
    Default: false
  BastionHostImageId:
    Description: "The image ID of the bastion host"
    Type: String
  BastionHostSSHKeyPair:
    Description: "The SSH key pair to be used by the bastion host"
    Type: String

Conditions:
  IsSno: 
    !Equals
      - true
      - !Ref CreateSnoCluster
  IsCompact: 
    !Equals
      - true
      - !Ref CreateCompactCluster
  CreateWorkerInstances:
    !And
      - !Not IsSno
      - !Not IsCompact
  CreateBationHost:
    !Equals
      - true
      - !Ref BationHostFlag

Resources:
  #             _                      _    
  #  _ __   ___| |___      _____  _ __| | __
  # | '_ \ / _ \ __\ \ /\ / / _ \| '__| |/ /
  # | | | |  __/ |_ \ V  V / (_) | |  |   < 
  # |_| |_|\___|\__| \_/\_/ \___/|_|  |_|\_\
  AYVPC:
    Type: "ALIYUN::ECS::VPC"
    Properties:
      CidrBlock:
        Ref: VpcCidrBlock
      RegionId:
        Ref: RegionId
      VpcName:
        Ref: VpcName

  AYVSwitchA:
    Type: "ALIYUN::ECS::VSwitch"
    Properties:
      VpcId:
        Ref: AYVPC
      ZoneId:
        !Select
          - '0'
          - !GetAZs
              Ref: RegionId
      CidrBlock:
        Ref: VSwitchCidrBlockA
      VSwitchName:
        Ref: VSwitchAName

  AYVSwitchB:
    Type: "ALIYUN::ECS::VSwitch"
    Properties:
      VpcId:
        Ref: AYVPC
      ZoneId:
        !Select
          - '1'
          - !GetAZs
              Ref: RegionId
      CidrBlock:
        Ref: VSwitchCidrBlockB
      VSwitchName:
        Ref: VSwitchBName

  AYSecurityGroup:
    Type: "ALIYUN::ECS::SecurityGroup"
    Properties:
      VpcId:
        Ref: AYVPC
      RegionId:
        Ref: RegionId
      SecurityGroupName:
        Ref: SecurityGroupName

  AYSecurityGroupIngressICMP:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: icmp
      PortRange: "-1/-1"
      SourceCidrIp: "0.0.0.0/0"

  # Rules for TCP
  AYSecurityGroupIngressTCP22:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "22/22"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressTCP1936:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "1936/1936"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressTCP9000_9999:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "9000/9999"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressTCP10250_10259:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "10250/10259"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressTCP10256:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "10256/10256"
      SourceCidrIp: "0.0.0.0/0"

  # Rules for UDP
  AYSecurityGroupIngressUDP4789:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "4789/4789"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP6081:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "6081/6081"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP9000_9999:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "9000/9999"
      SourceCidrIp: "0.0.0.0/0"
  
  AYSecurityGroupIngressUDP500:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "500/500"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP4500:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "4500/4500"
      SourceCidrIp: "0.0.0.0/0"

  # Rules for TCP/UDP
  AYSecurityGroupIngressTCP30000_32767:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "30000/32767"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP30000_32767:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "30000/32767"
      SourceCidrIp: "0.0.0.0/0"

  # TODO Those are only needed for control plane
  AYSecurityGroupIngressCPTCP2379_2380:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "2379/2380"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressCPTCP6443:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "6443/6443"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressCPTCP22:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "22/22"
      SourceCidrIp: "0.0.0.0/0"

  AYNLB:
    Type: "ALIYUN::NLB::LoadBalancer"
    Properties:
      AddressType: "Internet"
      RegionId:
        Ref: RegionId
      VpcId:
        Ref: AYVPC
      LoadBalancerName: ay-cluster-nlb
      CrossZoneEnabled: true
      ZoneMappings:
        - VSwitchId:
            Ref: AYVSwitchA
          ZoneId:
            !Select
              - '0'
              - !GetAZs
                  Ref: RegionId
        - VSwitchId:
            Ref: AYVSwitchB
          ZoneId:
            !Select
              - '1'
              - !GetAZs
                  Ref: RegionId

  AYNLBInternal:
    Type: "ALIYUN::NLB::LoadBalancer"
    Properties:
      AddressType: "Intranet"
      RegionId:
        Ref: RegionId
      VpcId:
        Ref: AYVPC
      LoadBalancerName: ay-cluster-nlb-internal
      CrossZoneEnabled: true
      ZoneMappings:
        - VSwitchId:
            Ref: AYVSwitchA
          ZoneId:
            !Select
              - '0'
              - !GetAZs
                  Ref: RegionId
        - VSwitchId:
            Ref: AYVSwitchB
          ZoneId:
            !Select
              - '1'
              - !GetAZs
                  Ref: RegionId

  # LISTENERS
  AYEIPA:
    Type: "ALIYUN::VPC::EIP"
    Properties:
      Bandwidth: "100"
      InternetChargeType: "PayByTraffic"

  AYNatGatewayA:
    Type: "ALIYUN::VPC::NatGateway"
    Properties:
      VpcId: !Ref AYVPC
      VSwitchId: !Ref AYVSwitchA

  AYEIPAAssociation:
    Type: "ALIYUN::VPC::EIPAssociation"
    Properties:
      AllocationId: !Ref AYEIPA
      InstanceId: !Ref AYNatGatewayA

  AYSnatEntryA:
    DependsOn: AYEIPAAssociation
    Type: ALIYUN::VPC::SnatEntry
    Properties:
      SourceVSwitchIds:
        - Ref: AYVSwitchA
      SnatIp:
        Fn::GetAtt:
          - AYEIPA
          - EipAddress          
      SnatTableId:
        Fn::GetAtt:
          - AYNatGatewayA
          - SNatTableId

  AYSnatEntryB:
    DependsOn: AYEIPAAssociation
    Type: ALIYUN::VPC::SnatEntry
    Properties:
      SourceVSwitchIds:
        - Ref: AYVSwitchB
      SnatIp:
        Fn::GetAtt:
          - AYEIPA
          - EipAddress          
      SnatTableId:
        Fn::GetAtt:
          - AYNatGatewayA
          - SNatTableId

  # ECS Instances
  AYSSHKeyPair:
    Type: ALIYUN::ECS::SSHKeyPair
    Properties:
      KeyPairName:
        Fn::Sub: ${EnvId}-ssh-key-pair
      PublicKeyBody:
        Ref: SSHPublicKeyBody

  AYBastionInstance:
    Count:
      !If
        - CreateBationHost
        - 1
        - 0
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName: 
        Fn::Sub: ${EnvId}-bastion-host
      HostName:
        Fn::Sub: ${EnvId}-bastion-host
      InstanceType:
        Ref: WorkerInstanceType
      ImageId:
        Ref: BastionHostImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        !Select
          - '0'
          - !GetAZs
              Ref: RegionId
      AllocatePublicIP: true
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: BastionHostSSHKeyPair

  AYMasterInstances:
    Type: "ALIYUN::ECS::Instance"
    Count: 
      !If
        - IsSno
        - 1
        - 3
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-master-${ALIYUN::Index}
      InstanceType:
        Ref: MasterInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId: 
        !Select
          - !Calculate
              - "{0}%2"
              - 0
              - - !Ref ALIYUN::Index
          - [!Ref AYVSwitchA, !Ref AYVSwitchB]
      ZoneId: 
        !Select
          - !Calculate
              - "{0}%2"
              - 0
              - - !Ref ALIYUN::Index
          - !GetAZs
              Ref: RegionId
      AllocatePublicIP: false
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Fn::GetAtt:
          - AYSSHKeyPair
          - KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-master-${ALIYUN::Index}
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/master
          Value: ""

  AYWorkerInstances:
    Type: "ALIYUN::ECS::Instance"
    Count: 
      !If
        - CreateWorkerInstances
        - 3
        - 0
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-worker-${ALIYUN::Index}
      InstanceType:
        Ref: WorkerInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId: 
        !Select
          - !Calculate
              - "{0}%2"
              - 0
              - - !Ref ALIYUN::Index
          - [!Ref AYVSwitchA, !Ref AYVSwitchB]
      ZoneId: 
        !Select
          - !Calculate
              - "{0}%2"
              - 0
              - - !Ref ALIYUN::Index
          - !GetAZs
              Ref: RegionId
      AllocatePublicIP: false
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Fn::GetAtt:
          - AYSSHKeyPair
          - KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-worker-${ALIYUN::Index}
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/master
          Value: ""
   
  AYWorkerServerGroup:
    Type: ALIYUN::NLB::ServerGroup
    Properties:
      ServerGroupName:
        Fn::Sub: ${EnvId}-workers
      VpcId: 
        Ref: AYVPC
      Protocol: TCP
      Servers:
        !If
          - CreateWorkerInstances
          - - ServerType: Ecs
              ServerId:
                Ref: AYWorkerInstances[0]
              Port: 443
            - ServerType: Ecs
              ServerId:
                Ref: AYWorkerInstances[1]
              Port: 443
            - ServerType: Ecs
              ServerId:
                Ref: AYWorkerInstances[2]
              Port: 443
          - !If
              - IsSno
              - - ServerType: Ecs
                  ServerId:
                    Ref: AYMasterInstances[0]
                  Port: 443
              - - ServerType: Ecs
                  ServerId:
                    Ref: AYMasterInstances[0]
                  Port: 443
                - ServerType: Ecs
                  ServerId:
                    Ref: AYMasterInstances[1]
                  Port: 443
                - ServerType: Ecs
                  ServerId:
                    Ref: AYMasterInstances[2]
                  Port: 443

  AYMasterServerGroup:
    DependsOn: 
      - AYMasterInstances
    Type: ALIYUN::NLB::ServerGroup
    Properties:
      ServerGroupName:
        Fn::Sub: ${EnvId}-masters
      VpcId: 
        Ref: AYVPC
      Protocol: TCP
      Servers:
        !If
          - IsSno
          - - ServerType: Ecs
              ServerId:
                Ref: AYMasterInstances[0]
              Port: 6443
          - - ServerType: Ecs
              ServerId:
                Ref: AYMasterInstances[0]
              Port: 6443
            - ServerType: Ecs
              ServerId:
                Ref: AYMasterInstances[1]
              Port: 6443
            - ServerType: Ecs
              ServerId:
                Ref: AYMasterInstances[2]
              Port: 6443

  NLBInternalListener6443:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLBInternal
      ListenerProtocol: TCP
      ListenerPort: 6443
      ServerGroupId: 
        Ref: AYMasterServerGroup

  NLBInternalListener22623:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLBInternal
      ListenerProtocol: TCP
      ListenerPort: 22623
      ServerGroupId: 
        Ref: AYMasterServerGroup

  NLBListener6443:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 6443
      ServerGroupId: 
        Ref: AYMasterServerGroup

  NLBListener80:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 80
      ServerGroupId: 
        Ref: AYWorkerServerGroup

  NLBListener443:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 443
      ServerGroupId: 
        Ref: AYWorkerServerGroup

  AYPrivateZone:
    Type: ALIYUN::PVTZ::Zone
    Properties:
      ZoneName: 
        Fn::Sub: ${ClusterName}.${DomainName}

  AYPrivateZoneVpcBinder:
    Type: ALIYUN::PVTZ::ZoneVpcBinder
    Properties:
      Vpcs:
        - VpcId:
            Ref: AYVPC
          RegionId:
            Ref: RegionId
      ZoneId:
        Fn::GetAtt:
          - AYPrivateZone
          - ZoneId

  AYPrivateZoneAPIRecord:
    Type: ALIYUN::PVTZ::ZoneRecord
    Properties:
      Rr: 'api'
      Value:
        Fn::GetAtt:
          - AYNLBInternal
          - DNSName
      ZoneId:
        Fn::GetAtt:
          - AYPrivateZone
          - ZoneId
      Type: CNAME

  AYPrivateZoneAPIINTRecord:
    Type: ALIYUN::PVTZ::ZoneRecord
    Properties:
      Rr: 'api-int'
      Value:
        Fn::GetAtt:
          - AYNLBInternal
          - DNSName
      ZoneId:
        Fn::GetAtt:
          - AYPrivateZone
          - ZoneId
      Type: CNAME

  AYPrivateZoneAPPSRecord:
    Type: ALIYUN::PVTZ::ZoneRecord
    Properties:
      Rr: '*.apps'
      Value:
        Fn::GetAtt:
          - AYNLBInternal
          - DNSName
      ZoneId:
        Fn::GetAtt:
          - AYPrivateZone
          - ZoneId
      Type: CNAME

  AYAPIRecord:
    Type: ALIYUN::DNS::DomainRecord
    Properties:
      DomainName:
        Ref: DomainName
      RR: 
        Fn::Sub: "api.${ClusterName}"
      Type: CNAME
      Value:
        Fn::GetAtt:
          - AYNLB
          - DNSName

  AYAPPSRecord:
    Type: ALIYUN::DNS::DomainRecord
    Properties:
      DomainName:
        Ref: DomainName
      RR: 
        Fn::Sub: "*.apps.${ClusterName}"
      Type: CNAME
      Value:
        Fn::GetAtt:
          - AYNLB
          - DNSName

Outputs:
  VPCID:
    Value:
      Ref: AYVPC
  VSwitchAID:
    Value:
      Ref: AYVSwitchA
  VSwitchBID:
    Value:
      Ref: AYVSwitchA
  SecurityGroupID:
    Value:
      Ref: AYSecurityGroup

