# aliyun ros CreateStack --StackName labay --TemplateURL 'file://template.ros.yaml' 

ROSTemplateFormatVersion: '2015-09-01'
Parameters:
  # General
  RegionId:
    Type: String
    Default: eu-central-1
  EnvId:
    Type: String
    Default: lab-ay1
  # Networking
  VpcCidrBlock:
    Type: String
    Default: '192.168.0.0/16'
  VpcName:
    Type: String
    Default: ay-cluster-vpc
  VSwitchCidrBlockA:
    Type: String
    Default: '192.168.1.0/24'
  VSwitchCidrBlockB:
    Type: String
    Default: '192.168.2.0/24'
  VSwitchAName:
    Type: String
    Default: ay-vswitch-a
  VSwitchBName:
    Type: String
    Default: ay-vswitch-b
  SecurityGroupName:
    Type: String
    Default: ay-cluster-sg
  ZoneAId:
    Type: String
    Default: eu-central-1a
  ZoneBId:
    Type: String
    Default: eu-central-1b
  # Security
  PublicKeyBody:
    Type: String
  # ECS
  InstallerInstanceType:
    Type: String
    Default: ecs.g6.xlarge
  InstallerSystemDiskSize:
    Type: Number
    Default: 200
  BootstrapInstanceType:
    Type: String
    Default: ecs.g6.xlarge
  BootstrapSystemDiskSize:
    Type: Number
    Default: 200
  RHCOSImageId:
    Type: String
    Default: m-gw8ei55k4akujv5mqvrv
  CentOSImageId:
    Type: String
    Default: m-gw8ei55k4akujv5mqvrv

Resources:
  AYVPC:
    Type: 'ALIYUN::ECS::VPC'
    Properties:
      CidrBlock: 
        Ref: VpcCidrBlock
      RegionId: 
        Ref: RegionId
      VpcName: 
        Ref: VpcName

  AYVSwitchA:
    Type: 'ALIYUN::ECS::VSwitch'
    Properties:
      VpcId:
        Ref: AYVPC
      ZoneId: 
        Ref: ZoneAId
      CidrBlock: 
        Ref: VSwitchCidrBlockA
      VSwitchName: 
        Ref: VSwitchAName
  
  AYVSwitchB:
    Type: 'ALIYUN::ECS::VSwitch'
    Properties:
      VpcId:
        Ref: AYVPC
      ZoneId: 
        Ref: ZoneBId
      CidrBlock: 
        Ref: VSwitchCidrBlockB
      VSwitchName: 
        Ref: VSwitchBName
  
  AYSecurityGroup:
    Type: 'ALIYUN::ECS::SecurityGroup'
    Properties:
      VpcId:
        Ref: AYVPC
      RegionId: 
        Ref: RegionId
      SecurityGroupName: 
        Ref: SecurityGroupName
  
  AYSecurityGroupIngressICMP:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: icmp
      PortRange: '-1/-1'
      SourceCidrIp: '0.0.0.0/0'
  
  # Rules for TCP
  AYSecurityGroupIngressTCP9000_9999:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: '9000/9999'
      SourceCidrIp: '0.0.0.0/0'
  
  AYSecurityGroupIngressTCP10250_10259:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: '10250/10259'
      SourceCidrIp: '0.0.0.0/0'
  
  AYSecurityGroupIngressTCP10256:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: '10256/10256'
      SourceCidrIp: '0.0.0.0/0'
  
  # Rules for UDP
  AYSecurityGroupIngressUDP4789:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: '4789/4789'
      SourceCidrIp: '0.0.0.0/0'
  
  AYSecurityGroupIngressUDP6081:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: '6081/6081'
      SourceCidrIp: '0.0.0.0/0'
  
  AYSecurityGroupIngressUDP9000_9999:
    Type: 'ALIYUN::ECS::SecurityGroupIngress'
    Properties:
      RegionId: 
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: '9000/9999'
      SourceCidrIp: '0.0.0.0/0'
  
  # Rules for TCP/UDP
  AYSecurityGroupIngressTCP30000_32767:
      Type: 'ALIYUN::ECS::SecurityGroupIngress'
      Properties:
        SecurityGroupId:
          Ref: AYSecurityGroup
        IpProtocol: tcp
        PortRange: '30000/32767'
        SourceCidrIp: '0.0.0.0/0'

  AYSecurityGroupIngressUDP30000_32767:
      Type: 'ALIYUN::ECS::SecurityGroupIngress'
      Properties:
        SecurityGroupId:
          Ref: AYSecurityGroup
        IpProtocol: udp
        PortRange: '30000/32767'
        SourceCidrIp: '0.0.0.0/0'
  
  # TODO Those are only needed for control plane
  AYSecurityGroupIngressCPTCP2379_2380:
      Type: 'ALIYUN::ECS::SecurityGroupIngress'
      Properties:
        SecurityGroupId:
          Ref: AYSecurityGroup
        IpProtocol: tcp
        PortRange: '2379/2380'
        SourceCidrIp: '0.0.0.0/0'

  AYSecurityGroupIngressCPTCP6443:
      Type: 'ALIYUN::ECS::SecurityGroupIngress'
      Properties:
        SecurityGroupId:
          Ref: AYSecurityGroup
        IpProtocol: tcp
        PortRange: '6443/6443'
        SourceCidrIp: '0.0.0.0/0'

  AYNLB:
    Type: 'ALIYUN::NLB::LoadBalancer'
    Properties:
      AddressType: 'Internet'
      RegionId: 
        Ref: RegionId
      VpcId: 
        Ref: AYVPC
      LoadBalancerName: ay-cluster-nlb
      ZoneMappings:
        - VSwitchId: 
            Ref: AYVSwitchA
          ZoneId: 
            Ref: ZoneAId
        - VSwitchId: 
            Ref: AYVSwitchB
          ZoneId: 
            Ref: ZoneBId
  

  AYSSHKeyPair:
    Type: ALIYUN::ECS::SSHKeyPair
    Properties:
      KeyPairName:
        Fn::Sub: ${EnvId}-keypair
      PublicKeyBody:
        Ref: PublicKeyBody

  AYInstallerInstance:
      Type: 'ALIYUN::ECS::Instance'
      DependsOn: AYSSHKeyPair
      Properties:
        InstanceName: installer
        InstanceType: 
          Ref: InstallerInstanceType
        ImageId: 
          Ref: RHCOSImageId
        SecurityGroupId: 
          Ref: AYSecurityGroup
        VSwitchId:
          Ref: AYVSwitchA
        ZoneId:
          Ref: ZoneAId
        UserData: |
          #!/bin/bash
          curl -sSL https://raw.githubusercontent.com/faermanj/lab-aliyun/main/ecs-init-installer.sh | bash

  AYSSHKeyPairAttachment:
     Type: ALIYUN::ECS::SSHKeyPairAttachment
     DependsOn:
       - AYSSHKeyPair
       - AYInstallerInstance
     Properties:
       KeyPairName: 
          Fn::GetAtt:
            - AYSSHKeyPair
            - KeyPairName
       InstanceIds:
         - Ref: AYInstallerInstance
  
  # BootstrapECS:
  #     Type: 'ALIYUN::ECS::Instance'
  #     Properties:
  #       InstanceType: 
  #         Ref: BootstrapInstanceType
  #       ImageId: 
  #         Ref: RHCOSImageId
  #       SystemDisk:
  #         Category: cloud_ssd
  #         Size: 
  #           Ref: BootstrapSystemDiskSize
  #       InstanceName: bootstrap
  #       SecurityGroupId: 
  #         Ref: AYSecurityGroup
  #       VSwitchId:
  #         Ref: AYVSwitchA
  #       ZoneId:
  #         Ref: ZoneAId

Outputs:
  VPCID:
    Value:
      Ref: AYVPC
  VSwitchAID:
    Value:
      Ref: AYVSwitchA
  VSwitchBID:
    Value:
      Ref: AYVSwitchA
  SecurityGroupID:
    Value:
      Ref: AYSecurityGroup
  InstallerInstanceID:
    Value:
      Ref: AYInstallerInstance
  InstallerInstancePublicIp:
    Value:
      Fn::GetAtt:
        - AYInstallerInstance
        - PublicIp
